services:
  radio-frontend:
    container_name: radio_frontend
    image: node:alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run start"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - DATABASE_URL="postgresql://"
      - LISTENBRAINZ_TOKEN=""
    restart: unless-stopped
    networks:
      - default