services:
  radio-frontend:
    container_name: radio_frontend
    build:
      context: ./radio
      dockerfile: Dockerfile
    image: radio-frontend:latest
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - DATABASE_URL="postgresql://"
      - LISTENBRAINZ_TOKEN=""
    restart: unless-stopped
    networks:
      - default
